# **DEEP LEARNING**

Name: **KERAS**  
Date : 2023  
Author: Aurélien Vannieuwenhuyze  


<a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/"><img alt="Licence Creative Commons" style="border-width:0" src="https://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png" /></a><br />This work is licensed under the terms of the <a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/">Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License.</a>.
<hr/>

##Initialisation des poids

In [10]:
import numpy as np
import matplotlib.pyplot as plt
import scipy.stats as stats
import math
from sklearn.metrics import mean_squared_error

### Initialisation entre -1 et 1

- Augmente le temps d'apprentissage
- Augmente le risque de Vanish gradient
- Diminue les performances.

In [11]:
def random_initialisation(F_in, F_out):
  borneMin = -1 
  borneMax = 1
  moyenne = 0
  ecartType = 1

  generateur = stats.truncnorm( (borneMin - moyenne) / ecartType, 
                       (borneMax - moyenne) / ecartType, 
                      loc=moyenne, 
                      scale=ecartType)
  return np.array(generateur.rvs(F_out*F_in))

In [12]:
poids = random_initialisation(3, 2)
print(poids)

[ 0.17310336 -0.39944395 -0.28444656  0.86542573 -0.0962923  -0.20497247]


### Initialisation avec Xavier Glorot

Si les poids du réseau de neurones sont trop petits, cela peut entrainer le problème de Vanish gradient (mort de certain neurones). S'il sont trop grand, le gradient "explose".  

L'explosition du gradient est un problème où des gradients d'erreur importants s'accumulent et entraînent des mises à jour très importantes des poids du modèle de réseau neuronal pendant l'apprentissage.  

Cela a pour effet de rendre le modèle instable et incapable d'apprendre à partir de vos données d'apprentissage.  

L'initialisation de Xavier Glorot permet de maintenir une variance lors de la phase propagation/ 

$$W^{[k]}_{i,j} \sim U \left[ -\frac{\sqrt{6}}{n_k+n{k-1}}, \frac{\sqrt{6}}{n_k+n{k-1}}\right]$$

In [13]:
def XavierGlorot(F_In, F_Out):
  borneMin = -(np.sqrt(6 / float(F_In + F_Out)))
  borneMax = np.sqrt(6 / float(F_In + F_Out))
  generateur = np.random.uniform(low=borneMin, high=borneMax, size=(F_In, F_Out))
  poids=[]
  for g in range(0,len(generateur)):
    poids.append(generateur[g][0])
    poids.append(generateur[g][1])
        
  return np.array(poids)

In [14]:
poids = XavierGlorot(3,2)
print(poids)

[-0.81198183 -0.49453267  0.835032    0.16185357 -0.74016589  0.65448481]


## Reseau de neurones multicouches avec Keras

In [15]:
#Generation de données
from sklearn.datasets import make_regression
X, y = make_regression(n_samples=5,n_features=2,n_informative=0,noise=12,coef=False)

X = np.interp(X, (X.min(), X.max()), (1, 5))
y = np.interp(y, (y.min(), y.max()), (0, 1))

In [16]:
X

array([[1.        , 2.86299092],
       [1.95816928, 3.36046767],
       [5.        , 4.44234635],
       [3.30691575, 1.26778104],
       [4.09514346, 3.56220458]])

In [17]:
y

array([0.38839181, 0.32336743, 0.31545417, 1.        , 0.        ])

In [18]:
from tensorflow import keras

keras_model = keras.Sequential()
keras_model.add(keras.layers.Input((2,)))
keras_model.add(keras.layers.Dense(3, activation='sigmoid', use_bias=True))
keras_model.add(keras.layers.Dense(1, activation='sigmoid', use_bias=True))

keras_model.compile(loss='mse')

2023-02-28 13:54:58.970262: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX_VNNI FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-02-28 13:54:59.074199: I tensorflow/core/util/port.cc:104] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2023-02-28 13:54:59.077578: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2023-02-28 13:54:59.077590: I tensorflow/compiler/xla/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudar

In [19]:
keras_model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 3)                 9         
                                                                 
 dense_1 (Dense)             (None, 1)                 4         
                                                                 
Total params: 13
Trainable params: 13
Non-trainable params: 0
_________________________________________________________________


In [20]:
print("COUCHE CACHEE 1")
poids = keras_model.layers[0].get_weights()[0]
biais = keras_model.layers[0].get_weights()[1]
print("poids : ",poids)
print("w1 :",str(poids[0][0]).replace(".",","))
print("w2 :",str(poids[1][0]).replace(".",","))
print("w3 :",str(poids[0][1]).replace(".",","))
print("w4 :",str(poids[1][1]).replace(".",","))
print("w5 :",str(poids[0][2]).replace(".",","))
print("w6 :",str(poids[1][2]).replace(".",","))
print("biais : ",biais)

print("\nCOUCHE SORTIE")
poids = keras_model.layers[1].get_weights()[0]
biais = keras_model.layers[1].get_weights()[1]
print("poids : ",poids)
print("w7 :",str(poids[0][0]).replace(".",","))
print("w8 :",str(poids[1][0]).replace(".",","))
print("w9 :",str(poids[2][0]).replace(".",","))

print("biais : ",biais)

COUCHE CACHEE 1
poids :  [[-0.6361194  -0.93312836 -0.42529523]
 [-0.80180013 -0.55270785  0.06360149]]
w1 : -0,6361194
w2 : -0,80180013
w3 : -0,93312836
w4 : -0,55270785
w5 : -0,42529523
w6 : 0,063601494
biais :  [0. 0. 0.]

COUCHE SORTIE
poids :  [[-0.82097197]
 [ 0.68288827]
 [ 0.83163583]]
w7 : -0,82097197
w8 : 0,68288827
w9 : 0,83163583
biais :  [0.]


In [21]:
class analyseEpoque(keras.callbacks.Callback):
    def __init__(self, x_test, y_test):
        self.x_test = x_test
        self.y_test = y_test
        
    def on_epoch_end(self, epoch, logs=None):
        print(self.x_test)
        print(self.y_test)
        y_pred = self.model.predict(self.x_test)
        print('Prédiction: {} a epoque: {}'.format(y_pred, epoch))
        print('Attendu: {} a epoque: {}'.format(self.y_test, epoch))

In [22]:
#Selection de la premiere observation pour étudier le comportement de Keras
X_train = np.array([X[0]])
y_train = np.array([y[0]])

print(X_train)
print(y_train)


[[1.         2.86299092]]
[0.38839181]


In [23]:
#Visualisation de la premiere epoch
keras_model.fit(X_train, y_train,  epochs=1,callbacks=[analyseEpoque(X_train,y_train)])

1/1 [==============================] - ETA: 0s - loss: 0.0417[[1.         2.86299092]]
[0.38839181]
1/1 [==============================] - 0s 43ms/step
Prédiction: [[0.5904014]] a epoque: 0
Attendu: [0.38839181] a epoque: 0
1/1 [==============================] - 0s 279ms/step - loss: 0.0417


## Regression avec Keras

In [24]:
#Generation de données
from sklearn.datasets import make_regression
import numpy as np
X, y = make_regression(n_samples=10000,n_features=5,n_informative=5,noise=12,coef=False)

X = np.interp(X, (X.min(), X.max()), (1, 20))
y = np.interp(y, (y.min(), y.max()), (1, 10))



In [25]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=42)

y_train


array([6.68076633, 6.17118866, 4.73263461, ..., 5.54799924, 6.06884668,
       7.04520474])

In [26]:
#Model 1 : Sigmoide
from tensorflow import keras

keras_model = keras.Sequential()
keras_model.add(keras.layers.Input((5,)))
keras_model.add(keras.layers.Dense(3, activation='sigmoid', use_bias=True))
keras_model.add(keras.layers.Dense(1, activation='sigmoid', use_bias=True))

keras_model.compile(loss='mse')

keras_model.fit(X_train, y_train,  epochs=50)

Epoch 1/50
219/219 [==============================] - 0s 837us/step - loss: 22.7164
Epoch 2/50
219/219 [==============================] - 0s 933us/step - loss: 21.6666
Epoch 3/50
219/219 [==============================] - 0s 987us/step - loss: 21.3571
Epoch 4/50
219/219 [==============================] - 0s 997us/step - loss: 21.2179
Epoch 5/50
219/219 [==============================] - 0s 905us/step - loss: 21.1567
Epoch 6/50
219/219 [==============================] - 0s 1ms/step - loss: 21.1303
Epoch 7/50
219/219 [==============================] - 0s 1ms/step - loss: 21.1188
Epoch 8/50
219/219 [==============================] - 0s 862us/step - loss: 21.1139
Epoch 9/50
219/219 [==============================] - 0s 879us/step - loss: 21.1118
Epoch 10/50
219/219 [==============================] - 0s 907us/step - loss: 21.1109
Epoch 11/50
219/219 [==============================] - 0s 707us/step - loss: 21.1105
Epoch 12/50
219/219 [==============================] - 0s 837us/step - loss: 2

In [27]:
predictions = keras_model.predict(X_test)

#Calcul de la RMSE
mean_squared_error(y_test, predictions, squared=False)

94/94 [==============================] - 0s 790us/step


4.603279163936314

In [28]:
#Model 2 : RELU
from tensorflow import keras

keras_model = keras.Sequential()
keras_model.add(keras.layers.Input((5,)))
keras_model.add(keras.layers.Dense(3, activation='relu', use_bias=True))
keras_model.add(keras.layers.Dense(1, activation='relu', use_bias=True))

keras_model.compile(loss='mse')

keras_model.fit(X_train, y_train,  epochs=50)

Epoch 1/50
219/219 [==============================] - 0s 1ms/step - loss: 10.1960
Epoch 2/50
219/219 [==============================] - 0s 864us/step - loss: 0.8567
Epoch 3/50
219/219 [==============================] - 0s 723us/step - loss: 0.5209
Epoch 4/50
219/219 [==============================] - 0s 825us/step - loss: 0.3867
Epoch 5/50
219/219 [==============================] - 0s 842us/step - loss: 0.3258
Epoch 6/50
219/219 [==============================] - 0s 774us/step - loss: 0.2891
Epoch 7/50
219/219 [==============================] - 0s 828us/step - loss: 0.2672
Epoch 8/50
219/219 [==============================] - 0s 665us/step - loss: 0.2500
Epoch 9/50
219/219 [==============================] - 0s 686us/step - loss: 0.2364
Epoch 10/50
219/219 [==============================] - 0s 764us/step - loss: 0.2247
Epoch 11/50
219/219 [==============================] - 0s 771us/step - loss: 0.2135
Epoch 12/50
219/219 [==============================] - 0s 1ms/step - loss: 0.2030
Epoc

In [29]:
predictions = keras_model.predict(X_test)

#Calcul de la RMSE
mean_squared_error(y_test, predictions, squared=False)

94/94 [==============================] - 0s 800us/step


0.12071862941612414

In [30]:
#Model 3 : RELU + ADAM
from tensorflow import keras

keras_model = keras.Sequential()
keras_model.add(keras.layers.Input((5,)))
keras_model.add(keras.layers.Dense(3, activation='relu', use_bias=True))
keras_model.add(keras.layers.Dense(1, activation='relu', use_bias=True))

keras_model.compile(loss='mse',optimizer='adam')

keras_model.fit(X_train, y_train,  epochs=50)

Epoch 1/50
219/219 [==============================] - 0s 904us/step - loss: 30.9745
Epoch 2/50
219/219 [==============================] - 0s 939us/step - loss: 30.9745
Epoch 3/50
219/219 [==============================] - 0s 859us/step - loss: 30.9745
Epoch 4/50
219/219 [==============================] - 0s 852us/step - loss: 30.9745
Epoch 5/50
219/219 [==============================] - 0s 820us/step - loss: 30.9745
Epoch 6/50
219/219 [==============================] - 0s 844us/step - loss: 30.9745
Epoch 7/50
219/219 [==============================] - 0s 1ms/step - loss: 30.9745
Epoch 8/50
219/219 [==============================] - 0s 1ms/step - loss: 30.9745
Epoch 9/50
219/219 [==============================] - 0s 944us/step - loss: 30.9745
Epoch 10/50
219/219 [==============================] - 0s 848us/step - loss: 30.9745
Epoch 11/50
219/219 [==============================] - 0s 893us/step - loss: 30.9745
Epoch 12/50
219/219 [==============================] - 0s 838us/step - loss: 3

In [31]:
#Prediction sur le test
predictions = keras_model.predict(X_test)

#Calcul de la RMSE
mean_squared_error(y_test, predictions, squared=False)



94/94 [==============================] - 0s 907us/step


5.574897444868813

In [32]:
keras_model.save("monModele.k")

INFO:tensorflow:Assets written to: monModele.k/assets


INFO:tensorflow:Assets written to: monModele.k/assets


In [33]:
monModele = keras.models.load_model("monModele.k")

In [34]:
indice_jeu_test = 0
print(X_test[indice_jeu_test])

print(X_test[indice_jeu_test].reshape(1,-1))

[10.56128664 12.58522689 11.46272687 11.77250366 12.87329833]
[[10.56128664 12.58522689 11.46272687 11.77250366 12.87329833]]


In [35]:
#Prediction d'un element
indice_jeu_test = 0
prediction = monModele.predict(X_test[indice_jeu_test].reshape(1,-1))
attendu = y_test[indice_jeu_test]
print("Attendu ",attendu,"- Prédit",prediction[0][0])

1/1 [==============================] - 0s 32ms/step
Attendu  6.095119458982135 - Prédit 0.0
